-- ============================================================================
-- COMPLETE DATABASE SETUP FOR RENTEASYINDIA
-- Run this ONCE to set up everything fresh
-- ============================================================================

-- Step 1: Drop existing tables (if any)
-- ============================================================================
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE booking_details CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE bookings CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE reviews CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cart CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE wishlist CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Step 2: Create tables
-- ============================================================================

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customername VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE NOT NULL,
    address VARCHAR2(500),
    password VARCHAR2(255) NOT NULL
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    description VARCHAR2(1000),
    image_path VARCHAR2(255),
    market_price NUMBER DEFAULT 0
);

CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    total_price NUMBER(10, 2),
    booking_date DATE DEFAULT SYSDATE,
    rent_date DATE NOT NULL,
    return_date DATE NOT NULL,
    status VARCHAR2(50) DEFAULT 'Confirmed',
    phone VARCHAR2(15),
    address VARCHAR2(500),
    location VARCHAR2(200),
    CONSTRAINT fk_cust_id FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE booking_details (
    booking_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    price NUMBER(10, 2),
    CONSTRAINT fk_booking_id FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    comment_text VARCHAR2(1000),
    verdict VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE cart (
    cart_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE wishlist (
    wishlist_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

COMMIT;

-- ============================================================================
-- Step 3: Insert data (will be done by Python script)
-- ============================================================================
-- Run: python COMPLETE_SETUP.py after running this SQL file
-- ============================================================================
