BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE booking_details CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE bookings CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE customers CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE reviews CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE cart CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE wishlist CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE products_backup CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE bookings_backup CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE booking_details_backup CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE customers_backup CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customername VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE NOT NULL,
    address VARCHAR2(500),
    password VARCHAR2(255) NOT NULL
);

CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    description VARCHAR2(1000),
    image_path VARCHAR2(255),
    market_price NUMBER DEFAULT 0
);

CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    total_price NUMBER(10, 2),
    booking_date DATE DEFAULT SYSDATE,
    rent_date DATE NOT NULL,
    return_date DATE NOT NULL,
    status VARCHAR2(50) DEFAULT 'Confirmed',
    phone VARCHAR2(15),
    address VARCHAR2(500),
    location VARCHAR2(200),
    CONSTRAINT fk_cust_id FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE booking_details (
    booking_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    price NUMBER(10, 2),
    CONSTRAINT fk_booking_id FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE reviews (
    review_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    comment_text VARCHAR2(1000),
    verdict VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

CREATE TABLE cart (
    cart_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

CREATE TABLE wishlist (
    wishlist_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

INSERT INTO customers (customername, phone, email, password, address) VALUES ('Rahul Sharma', '9876543210', 'rahul@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Pune');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Priya Deshmukh', '9876543211', 'priya.d@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Mumbai');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Arjun Patel', '9123456789', 'arjun.p@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Ahmedabad');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Sneha Reddy', '9234567890', 'sneha.r@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Hyderabad');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Vikram Singh', '9345678901', 'vikram.s@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Jaipur');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Ananya Iyer', '9456789012', 'ananya.i@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Chennai');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Rohan Mehta', '9567890123', 'rohan.m@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Pune');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Kavya Nair', '9678901234', 'kavya.n@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Kochi');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Aditya Gupta', '9789012345', 'aditya.g@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Delhi');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Ishita Joshi', '9890123456', 'ishita.j@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Bangalore');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Karan Kapoor', '9901234567', 'karan.k@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Chandigarh');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Meera Kulkarni', '9012345678', 'meera.k@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Nashik');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Siddharth Rao', '9123450987', 'siddharth.r@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Mysore');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Tanvi Shah', '9234561098', 'tanvi.s@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Surat');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Nikhil Verma', '9345672109', 'nikhil.v@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Lucknow');
INSERT INTO customers (customername, phone, email, password, address) VALUES ('Riya Malhotra', '9456783210', 'riya.m@gmail.com', 'pbkdf2:sha256:600000$abc123', 'Kolkata');

INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Premium Blazer', 'Mens', 3500, '/static/images/mens10.jpg', 7000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Sapphire Premium Set', 'Jewelry', 4500, '/static/images/sapphire_premium.png', 9000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Emerald Solitaire Ring', 'Jewelry', 8000, '/static/images/ring1.jpg', 16000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Antique Temple Set', 'Jewelry', 5200, '/static/images/temple_set.jpg', 10400);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Pearl Choker Necklace', 'Jewelry', 1400, '/static/images/pearl_choker.jpg', 2800);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Ruby Wedding Set', 'Jewelry', 13000, '/static/images/ruby_set.jpg', 26000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Royal Maroon Lehenga', 'Womens', 11000, '/static/images/womens1.jpg', 22000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Emerald Silk Gown', 'Womens', 10500, '/static/images/womens2.jpg', 21000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Bridal Red Anarkali', 'Womens', 12400, '/static/images/womens3.jpg', 24800);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Designer Saree', 'Womens', 6750, '/static/images/womens4.jpg', 13500);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Royal Blue Sherwani', 'Mens', 16250, '/static/images/mens1.jpg', 32500);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Black Tuxedo', 'Mens', 2600, '/static/images/mens2.jpg', 5200);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Grey Office Suit', 'Mens', 5850, '/static/images/mens3.jpg', 11700);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Cream Wedding Kurta', 'Mens', 7000, '/static/images/mens4.jpg', 14000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Navy Blazer', 'Mens', 10500, '/static/images/mens5.jpg', 21000);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Maroon Sherwani', 'Mens', 14400, '/static/images/mens6.jpg', 28800);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('White Formal Shirt', 'Mens', 750, '/static/images/mens7.jpg', 1500);
INSERT INTO products (name, category, price, image_path, market_price) VALUES ('Brown Leather Jacket', 'Mens', 8250, '/static/images/mens8.jpg', 16500);

INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (1, 3500, TO_DATE('10-FEB-26', 'DD-MON-YY'), TO_DATE('13-FEB-26', 'DD-MON-YY'), 'Confirmed', '9876543210', 'Pune', 'Pune');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (2, 4500, TO_DATE('11-FEB-26', 'DD-MON-YY'), TO_DATE('14-FEB-26', 'DD-MON-YY'), 'Pending', '9876543211', 'Mumbai', 'Mumbai');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (3, 8000, TO_DATE('12-FEB-26', 'DD-MON-YY'), TO_DATE('15-FEB-26', 'DD-MON-YY'), 'Returned', '9123456789', 'Ahmedabad', 'Ahmedabad');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (4, 5200, TO_DATE('13-FEB-26', 'DD-MON-YY'), TO_DATE('16-FEB-26', 'DD-MON-YY'), 'Confirmed', '9234567890', 'Hyderabad', 'Hyderabad');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (5, 1400, TO_DATE('14-FEB-26', 'DD-MON-YY'), TO_DATE('17-FEB-26', 'DD-MON-YY'), 'Pending', '9345678901', 'Jaipur', 'Jaipur');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (6, 13000, TO_DATE('15-FEB-26', 'DD-MON-YY'), TO_DATE('18-FEB-26', 'DD-MON-YY'), 'Returned', '9456789012', 'Chennai', 'Chennai');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (7, 11000, TO_DATE('16-FEB-26', 'DD-MON-YY'), TO_DATE('19-FEB-26', 'DD-MON-YY'), 'Confirmed', '9567890123', 'Pune', 'Pune');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (8, 10500, TO_DATE('17-FEB-26', 'DD-MON-YY'), TO_DATE('20-FEB-26', 'DD-MON-YY'), 'Pending', '9678901234', 'Kochi', 'Kochi');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (9, 12400, TO_DATE('18-FEB-26', 'DD-MON-YY'), TO_DATE('21-FEB-26', 'DD-MON-YY'), 'Returned', '9789012345', 'Delhi', 'Delhi');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (10, 6750, TO_DATE('19-FEB-26', 'DD-MON-YY'), TO_DATE('22-FEB-26', 'DD-MON-YY'), 'Confirmed', '9890123456', 'Bangalore', 'Bangalore');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (11, 16250, TO_DATE('20-FEB-26', 'DD-MON-YY'), TO_DATE('23-FEB-26', 'DD-MON-YY'), 'Pending', '9901234567', 'Chandigarh', 'Chandigarh');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (12, 2600, TO_DATE('21-FEB-26', 'DD-MON-YY'), TO_DATE('24-FEB-26', 'DD-MON-YY'), 'Returned', '9012345678', 'Nashik', 'Nashik');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (13, 5850, TO_DATE('22-FEB-26', 'DD-MON-YY'), TO_DATE('25-FEB-26', 'DD-MON-YY'), 'Confirmed', '9123450987', 'Mysore', 'Mysore');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (14, 7000, TO_DATE('23-FEB-26', 'DD-MON-YY'), TO_DATE('26-FEB-26', 'DD-MON-YY'), 'Pending', '9234561098', 'Surat', 'Surat');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (15, 10500, TO_DATE('24-FEB-26', 'DD-MON-YY'), TO_DATE('27-FEB-26', 'DD-MON-YY'), 'Returned', '9345672109', 'Lucknow', 'Lucknow');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (16, 14400, TO_DATE('25-FEB-26', 'DD-MON-YY'), TO_DATE('28-FEB-26', 'DD-MON-YY'), 'Confirmed', '9456783210', 'Kolkata', 'Kolkata');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (1, 750, TO_DATE('26-FEB-26', 'DD-MON-YY'), TO_DATE('01-MAR-26', 'DD-MON-YY'), 'Pending', '9876543210', 'Pune', 'Pune');
INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location) VALUES (2, 8250, TO_DATE('27-FEB-26', 'DD-MON-YY'), TO_DATE('02-MAR-26', 'DD-MON-YY'), 'Returned', '9876543211', 'Mumbai', 'Mumbai');

INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (1, 1, 1, 3500);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (2, 2, 1, 4500);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (3, 3, 1, 8000);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (4, 4, 1, 5200);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (5, 5, 1, 1400);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (6, 6, 1, 13000);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (7, 7, 1, 11000);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (8, 8, 1, 10500);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (9, 9, 1, 12400);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (10, 10, 1, 6750);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (11, 11, 1, 16250);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (12, 12, 1, 2600);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (13, 13, 1, 5850);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (14, 14, 1, 7000);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (15, 15, 1, 10500);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (16, 16, 1, 14400);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (17, 17, 1, 750);
INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (18, 18, 1, 8250);

COMMIT;

SELECT * FROM customers ORDER BY customer_id;

SELECT * FROM products ORDER BY product_id;

SELECT * FROM bookings ORDER BY booking_id;

SELECT 
    b.booking_id AS "Booking ID",
    c.customername AS "Customer Name",
    p.name AS "Product Name",
    b.total_price AS "Total Price",
    b.rent_date AS "Rent Date",
    b.return_date AS "Return Date",
    b.status AS "Status"
FROM bookings b
JOIN customers c ON b.customer_id = c.customer_id
JOIN booking_details bd ON b.booking_id = bd.booking_id
JOIN products p ON bd.product_id = p.product_id
ORDER BY b.booking_id;
