from db import get_connection
from werkzeug.security import generate_password_hash

print("="*80)
print("COMPLETE DATABASE REPLACEMENT - FRESH START")
print("="*80)

conn = get_connection()
cur = conn.cursor()

# Step 1: Drop all tables
print("\n1. Dropping existing tables...")
tables_to_drop = ['booking_details', 'bookings', 'products', 'customers', 'reviews', 'cart', 'wishlist',
                  'products_backup', 'bookings_backup', 'booking_details_backup', 'customers_backup']

for table in tables_to_drop:
    try:
        cur.execute(f"DROP TABLE {table} CASCADE CONSTRAINTS")
        print(f"   Dropped {table}")
    except:
        pass

conn.commit()

# Step 2: Create tables
print("\n2. Creating tables...")

cur.execute("""
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customername VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE NOT NULL,
    address VARCHAR2(500),
    password VARCHAR2(255) NOT NULL
)
""")

cur.execute("""
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    description VARCHAR2(1000),
    image_path VARCHAR2(255),
    market_price NUMBER DEFAULT 0
)
""")

cur.execute("""
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    total_price NUMBER(10, 2),
    booking_date DATE DEFAULT SYSDATE,
    rent_date DATE NOT NULL,
    return_date DATE NOT NULL,
    status VARCHAR2(50) DEFAULT 'Confirmed',
    phone VARCHAR2(15),
    address VARCHAR2(500),
    location VARCHAR2(200),
    CONSTRAINT fk_cust_id FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
)
""")

cur.execute("""
CREATE TABLE booking_details (
    booking_detail_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    price NUMBER(10, 2),
    CONSTRAINT fk_booking_id FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
    CONSTRAINT fk_product_id FOREIGN KEY (product_id) REFERENCES products(product_id)
)
""")

cur.execute("""
CREATE TABLE reviews (
    review_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    rating NUMBER(1) CHECK (rating BETWEEN 1 AND 5),
    comment_text VARCHAR2(1000),
    verdict VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (product_id) REFERENCES products(product_id),
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
)
""")

cur.execute("""
CREATE TABLE cart (
    cart_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
)
""")

cur.execute("""
CREATE TABLE wishlist (
    wishlist_id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    FOREIGN KEY (product_id) REFERENCES products(product_id)
)
""")

conn.commit()
print("   All tables created")

# Step 3: Insert Customers
print("\n3. Inserting 16 customers...")
customers_data = [
    ("Rahul Sharma", "9876543210", "rahul@gmail.com", "Pune"),
    ("Priya Deshmukh", "9876543211", "priya.d@gmail.com", "Mumbai"),
    ("Arjun Patel", "9123456789", "arjun.p@gmail.com", "Ahmedabad"),
    ("Sneha Reddy", "9234567890", "sneha.r@gmail.com", "Hyderabad"),
    ("Vikram Singh", "9345678901", "vikram.s@gmail.com", "Jaipur"),
    ("Ananya Iyer", "9456789012", "ananya.i@gmail.com", "Chennai"),
    ("Rohan Mehta", "9567890123", "rohan.m@gmail.com", "Pune"),
    ("Kavya Nair", "9678901234", "kavya.n@gmail.com", "Kochi"),
    ("Aditya Gupta", "9789012345", "aditya.g@gmail.com", "Delhi"),
    ("Ishita Joshi", "9890123456", "ishita.j@gmail.com", "Bangalore"),
    ("Karan Kapoor", "9901234567", "karan.k@gmail.com", "Chandigarh"),
    ("Meera Kulkarni", "9012345678", "meera.k@gmail.com", "Nashik"),
    ("Siddharth Rao", "9123450987", "siddharth.r@gmail.com", "Mysore"),
    ("Tanvi Shah", "9234561098", "tanvi.s@gmail.com", "Surat"),
    ("Nikhil Verma", "9345672109", "nikhil.v@gmail.com", "Lucknow"),
    ("Riya Malhotra", "9456783210", "riya.m@gmail.com", "Kolkata"),
]

for name, phone, email, address in customers_data:
    hashed_pw = generate_password_hash("password123")
    cur.execute("""
        INSERT INTO customers (customername, phone, email, password, address)
        VALUES (:1, :2, :3, :4, :5)
    """, (name, phone, email, hashed_pw, address))

conn.commit()
print(f"   Inserted {len(customers_data)} customers")

# Step 4: Insert Products
print("\n4. Inserting 18 products...")
products_data = [
    ("Premium Blazer", "Mens", 3500, "/static/images/mens10.jpg", 7000),
    ("Sapphire Premium Set", "Jewelry", 4500, "/static/images/sapphire_premium.png", 9000),
    ("Emerald Solitaire Ring", "Jewelry", 8000, "/static/images/ring1.jpg", 16000),
    ("Antique Temple Set", "Jewelry", 5200, "/static/images/temple_set.jpg", 10400),
    ("Pearl Choker Necklace", "Jewelry", 1400, "/static/images/pearl_choker.jpg", 2800),
    ("Ruby Wedding Set", "Jewelry", 13000, "/static/images/ruby_set.jpg", 26000),
    ("Royal Maroon Lehenga", "Womens", 11000, "/static/images/womens1.jpg", 22000),
    ("Emerald Silk Gown", "Womens", 10500, "/static/images/womens2.jpg", 21000),
    ("Bridal Red Anarkali", "Womens", 12400, "/static/images/womens3.jpg", 24800),
    ("Designer Saree", "Womens", 6750, "/static/images/womens4.jpg", 13500),
    ("Royal Blue Sherwani", "Mens", 16250, "/static/images/mens1.jpg", 32500),
    ("Black Tuxedo", "Mens", 2600, "/static/images/mens2.jpg", 5200),
    ("Grey Office Suit", "Mens", 5850, "/static/images/mens3.jpg", 11700),
    ("Cream Wedding Kurta", "Mens", 7000, "/static/images/mens4.jpg", 14000),
    ("Navy Blazer", "Mens", 10500, "/static/images/mens5.jpg", 21000),
    ("Maroon Sherwani", "Mens", 14400, "/static/images/mens6.jpg", 28800),
    ("White Formal Shirt", "Mens", 750, "/static/images/mens7.jpg", 1500),
    ("Brown Leather Jacket", "Mens", 8250, "/static/images/mens8.jpg", 16500),
]

for name, category, price, image, market_price in products_data:
    cur.execute("""
        INSERT INTO products (name, category, price, image_path, market_price)
        VALUES (:1, :2, :3, :4, :5)
    """, (name, category, price, image, market_price))

conn.commit()
print(f"   Inserted {len(products_data)} products")

# Step 5: Insert Bookings
print("\n5. Inserting 18 bookings...")
import datetime
base_date = datetime.date(2026, 2, 10)

for i in range(18):
    customer_id = (i % 16) + 1
    product_id = i + 1
    rent_date = base_date + datetime.timedelta(days=i)
    return_date = rent_date + datetime.timedelta(days=3)
    
    # Get product price
    cur.execute("SELECT price FROM products WHERE product_id = :1", (product_id,))
    price = cur.fetchone()[0]
    
    # Determine status
    if i % 3 == 0:
        status = 'Confirmed'
    elif i % 3 == 1:
        status = 'Pending'
    else:
        status = 'Returned'
    
    cur.execute("""
        INSERT INTO bookings (customer_id, total_price, rent_date, return_date, status, phone, address, location)
        VALUES (:1, :2, :3, :4, :5, :6, :7, :8)
    """, (customer_id, price, rent_date, return_date, status, '9876543210', 'Address', 'Location'))
    
    # Get the booking_id that was just inserted
    cur.execute("SELECT booking_id FROM bookings WHERE customer_id = :1 AND rent_date = :2", (customer_id, rent_date))
    booking_id = cur.fetchone()[0]
    
    # Insert booking detail
    cur.execute("""
        INSERT INTO booking_details (booking_id, product_id, quantity, price)
        VALUES (:1, :2, 1, :3)
    """, (booking_id, product_id, price))

conn.commit()
print(f"   Inserted 18 bookings with details")

# Final verification
print("\n" + "="*80)
print("FINAL VERIFICATION:")
print("="*80)

cur.execute("SELECT COUNT(*) FROM customers")
customers = cur.fetchone()[0]
print(f"Customers: {customers}")

cur.execute("SELECT COUNT(*) FROM products")
products = cur.fetchone()[0]
print(f"Products: {products}")

cur.execute("SELECT COUNT(*) FROM bookings")
bookings = cur.fetchone()[0]
print(f"Bookings: {bookings}")

cur.execute("SELECT COUNT(*) FROM booking_details")
booking_details = cur.fetchone()[0]
print(f"Booking Details: {booking_details}")

print("\n" + "="*80)
print("[SUCCESS] Fresh database created!")
print("="*80)
print("\nYou now have:")
print("- 16 customers with diverse names")
print("- 18 products (Jewelry, Mens, Womens)")
print("- 18 bookings (Confirmed, Pending, Returned)")
print("- Properly normalized (1NF, 2NF, 3NF)")
print("\nYour website and database are ready for presentation!")
print("="*80)

cur.close()
conn.close()
