-- RentEasy India - Database Schema (Synthesized)
-- Use this file as a reference for the Oracle database structure.

-- 1. CUSTOMERS
CREATE TABLE customers (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customername VARCHAR2(100) NOT NULL,
    phone VARCHAR2(20),
    email VARCHAR2(100) UNIQUE NOT NULL,
    address VARCHAR2(500),
    password VARCHAR2(255) NOT NULL
);

-- 2. ADMINS
CREATE TABLE admins (
    admin_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(100) UNIQUE NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. PRODUCTS
CREATE TABLE products (
    product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(255) NOT NULL,
    category VARCHAR2(100) NOT NULL,
    price NUMBER(10, 2) NOT NULL,
    description VARCHAR2(1000),
    image_path VARCHAR2(255)
);

-- 4. BOOKINGS
CREATE TABLE bookings (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    total_price NUMBER(10, 2) NOT NULL,
    booking_date DATE DEFAULT SYSDATE,
    rent_date DATE NOT NULL,
    return_date DATE NOT NULL,
    status VARCHAR2(50) DEFAULT 'Confirmed',
    phone VARCHAR2(20),
    address VARCHAR2(500),
    location VARCHAR2(255),
    CONSTRAINT fk_booking_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_booking_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- 5. WISHLIST
CREATE TABLE wishlist (
    wishlist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    CONSTRAINT fk_wishlist_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_wishlist_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- 6. CART
CREATE TABLE cart (
    cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_cart_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    CONSTRAINT fk_cart_product FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- 7. REVIEWS
CREATE TABLE reviews (
    review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER NOT NULL,
    customer_id NUMBER NOT NULL,
    rating NUMBER CHECK (rating BETWEEN 1 AND 5),
    comment_text VARCHAR2(1000),
    verdict VARCHAR2(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_review_product FOREIGN KEY (product_id) REFERENCES products(product_id),
    CONSTRAINT fk_review_customer FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
