import oracledb
from db import get_connection
from datetime import datetime, timedelta

def sync_database():
    """
    ULTRA MASTER SYNC: 
    Restores 44+ Products, 15+ Bookings, and ALL functional tables.
    Matches Template Indices (Image at index 4).
    """
    print("Starting Final Master Presentation Sync...")
    
    try:
        conn = get_connection()
        cur = conn.cursor()
        
        # 1. DROP ALL TABLES (Complete Clear)
        print("- Resetting all structures...")
        tables = ['payments', 'reviews', 'wishlist', 'cart', 'booking_details', 'bookings', 'products', 'customers']
        for t in tables:
            try: cur.execute(f"DROP TABLE {t} CASCADE CONSTRAINTS")
            except: pass
        
        # 2. CREATE EVERY TABLE NEEDED
        print("- Rebuilding Zero-Error Schema...")
        
        cur.execute("""
            CREATE TABLE customers (
                customer_id NUMBER PRIMARY KEY,
                customername VARCHAR2(100) NOT NULL,
                phone VARCHAR2(20),
                email VARCHAR2(100) UNIQUE NOT NULL,
                address VARCHAR2(500),
                password VARCHAR2(255) NOT NULL
            )
        """)

        cur.execute("""
            CREATE TABLE products (
                product_id NUMBER PRIMARY KEY,
                name VARCHAR2(255) NOT NULL,
                category VARCHAR2(100) NOT NULL,
                price NUMBER(10, 2) NOT NULL,
                image_path VARCHAR2(255),
                description VARCHAR2(1000),
                market_price NUMBER(10, 2)
            )
        """)

        cur.execute("""
            CREATE TABLE bookings (
                booking_id NUMBER PRIMARY KEY,
                customer_id NUMBER NOT NULL,
                total_price NUMBER(10, 2) NOT NULL,
                booking_date DATE DEFAULT SYSDATE,
                rent_date DATE NOT NULL,
                return_date DATE NOT NULL,
                status VARCHAR2(50) DEFAULT 'Confirmed',
                phone VARCHAR2(20),
                address VARCHAR2(500),
                location VARCHAR2(255),
                CONSTRAINT fk_b_cust_master FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
            )
        """)
        
        cur.execute("""
            CREATE TABLE booking_details (
                booking_id NUMBER NOT NULL,
                product_id NUMBER NOT NULL,
                quantity NUMBER DEFAULT 1,
                price NUMBER(10, 2),
                CONSTRAINT fk_bd_b_master FOREIGN KEY (booking_id) REFERENCES bookings(booking_id),
                CONSTRAINT fk_bd_p_master FOREIGN KEY (product_id) REFERENCES products(product_id)
            )
        """)

        cur.execute("""
            CREATE TABLE reviews (
                review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                product_id NUMBER NOT NULL,
                customer_id NUMBER NOT NULL,
                rating NUMBER CHECK (rating BETWEEN 1 AND 5),
                comment_text VARCHAR2(1000),
                verdict VARCHAR2(50),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_rev_p FOREIGN KEY (product_id) REFERENCES products(product_id),
                CONSTRAINT fk_rev_c FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
            )
        """)

        cur.execute("""
            CREATE TABLE cart (
                cart_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id NUMBER NOT NULL,
                product_id NUMBER NOT NULL,
                quantity NUMBER DEFAULT 1,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_cart_c FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
                CONSTRAINT fk_cart_p FOREIGN KEY (product_id) REFERENCES products(product_id)
            )
        """)

        cur.execute("""
            CREATE TABLE wishlist (
                wishlist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id NUMBER NOT NULL,
                product_id NUMBER NOT NULL,
                CONSTRAINT fk_wish_c FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
                CONSTRAINT fk_wish_p FOREIGN KEY (product_id) REFERENCES products(product_id)
            )
        """)

        # 3. POPULATE MASSIVE 44-ITEM CATALOG
        print("- Restoring 44 Products (Image at index 4)...")
        all_products = [
            # JEWELRY (12 Items)
            (101, 'Sapphire Premium Set', 'Jewelry', 4500, '/static/images/sapphire_premium.png', 'Royal blue sapphire necklace with matching earrings.', 120000),
            (102, 'Diamond Studded Bangles', 'Jewelry', 2800, '/static/images/jwelery1.jpg', 'Exquisite diamond-cut gold bangles.', 85000),
            (103, 'Ethnic Gold Choker', 'Jewelry', 3500, '/static/images/jwelery2.jpg', 'Traditional Indian bridal choker.', 95000),
            (104, 'Ruby Pendant Set', 'Jewelry', 2200, '/static/images/jwelery3.jpg', 'Modern ruby pendant for cocktail nights.', 45000),
            (105, 'Pearl String Necklace', 'Jewelry', 3000, '/static/images/jwelery4.jpg', 'Classic South Sea pearl necklace.', 60000),
            (106, 'Kundan Jhumka Earrings', 'Jewelry', 1800, '/static/images/jwelery5.jpg', 'Traditional handcrafted kundan work.', 35000),
            (107, 'Silver Filigree Bracelet', 'Jewelry', 1500, '/static/images/bracelet1.jpg', 'Delicate vintage silver design.', 12000),
            (108, 'Emerald Solitaire Ring', 'Jewelry', 1200, '/static/images/ring1.jpg', 'Large emerald in white gold.', 25000),
            (109, 'Antique Temple Set', 'Jewelry', 3800, '/static/images/jwelery_update_2.jpg', 'Traditional temple jewelry for weddings.', 110000),
            (110, 'Swarovski Crystal Set', 'Jewelry', 2900, '/static/images/jwelery_update_3.jpg', 'Contemporary crystal jewelry.', 40000),
            (111, 'Rose Gold Chrono Watch', 'Jewelry', 4000, '/static/images/jwelery_update_1.jpg', 'Designer watch for grand events.', 55000),
            (112, 'Platinum Engagement Band', 'Jewelry', 2500, '/static/images/ring2.jpg', 'Pure platinum matte finish.', 80000),

            # WOMEN'S WEAR (10 Items)
            (201, 'Royal Maroon Lehenga', 'Dresses', 5500, '/static/images/royal_lehenga.png', 'Heavy bridal lehenga with zardozi.', 65000),
            (202, 'Emerald Silk Gown', 'Dresses', 4200, '/static/images/emerald_gown.png', 'Long satin gown for red carpet look.', 50000),
            (203, 'Navy Designer Saree', 'Dresses', 3200, '/static/images/women8.jpg', 'Heavily embroidered wedding saree.', 35000),
            (204, 'Golden Sequin Dress', 'Dresses', 3800, '/static/images/women9.jpg', 'Stunning sequins for gala nights.', 42000),
            (205, 'Bridal Red Anarkali', 'Dresses', 4500, '/static/images/women10.jpg', 'Traditional floor-length ethnic wear.', 55000),
            (206, 'Pastel Silk Lehenga', 'Dresses', 4800, '/static/images/women3.jpg', 'Modern pastel shades for bridesmaids.', 52000),
            (207, 'Contemporary Fusion Set', 'Dresses', 3100, '/static/images/women6.jpg', 'Indo-western style for receptions.', 30000),
            (208, 'Banarasi Silk Saree', 'Dresses', 2800, '/static/images/women4.jpg', 'Classic Banarasi weave for elegance.', 32000),
            (209, 'Floral Georgette Dress', 'Dresses', 1800, '/static/images/women2.jpg', 'Lightweight and stylish for haldi.', 20000),
            (210, 'Designer Salwar Suite', 'Dresses', 2400, '/static/images/women5.jpg', 'Perfect for festive day events.', 22000),

            # MEN'S WEAR (8 Items)
            (301, 'Executive Black Blazer', 'Mens', 3500, '/static/images/mens10.jpg', 'Premium wool-blend tailored blazer.', 42000),
            (302, 'Indigo Designer Kurta', 'Mens', 2200, '/static/images/mens1.jpg', 'Stylish asymmetric ethnic wear.', 26000),
            (303, 'Royal Sherwani Set', 'Mens', 5500, '/static/images/mens3.jpg', 'Exquisite wedding sherwani.', 85000),
            (304, 'Grey Formal Suit', 'Mens', 4200, '/static/images/mens2.jpg', 'Complete 3-piece formal attire.', 50000),
            (305, 'Embroidered Waistcoat', 'Mens', 1800, '/static/images/mens5.jpg', 'Enhance any simple kurta.', 15000),
            (306, 'Classic Bandhgala', 'Mens', 4500, '/static/images/mens7.jpg', 'Traditional Rajasthani coat.', 55000),
            (307, 'Linen Ivory Shirt', 'Mens', 1200, '/static/images/mens4.jpg', 'Premium Italian linen shirt.', 22000),
            (308, 'Traditional Pathani', 'Mens', 2500, '/static/images/mens6.jpg', 'Pathani suit with heavy work.', 28000),

            # DECOR (8 Items)
            (401, 'Grand Stage Decor', 'Decor', 15000, '/static/images/decor12.jpg', 'Full wedding stage backdrop setup.', 150000),
            (402, 'Floral Entry Gate', 'Decor', 8000, '/static/images/decor9.jpg', 'Fresh flower gate for guests.', 45000),
            (403, 'Outdoor Garden Setup', 'Decor', 12000, '/static/images/decor2.jpg', 'Complete theme for garden lawn.', 120000),
            (404, 'Modern Mandap Set', 'Decor', 25000, '/static/images/decor1.jpg', 'Exclusive 4-pillar mandap setup.', 250000),
            (405, 'Fairy Light Drape', 'Decor', 3000, '/static/images/decor11.jpg', 'Complete hall lighting ambiance.', 250000),
            (406, 'Banquet Centerpiece', 'Decor', 1500, '/static/images/decor10.jpg', 'Elegant floral table setup.', 40000),
            (407, 'Lounge Furniture Hire', 'Decor', 5000, '/static/images/decor3.jpg', 'Classic sofas and coffee tables.', 60000),
            (408, 'Theme Lighting Rig', 'Decor', 7000, '/static/images/decor4.jpg', 'Moving heads and LED wash lights.', 75000),

            # EVENT TOOLS (6 Items)
            (501, 'Pro DSLR Camera Kit', 'Event Tools', 2500, '/static/images/event_tool3.jpg', 'Full photography kit with lenses.', 180000),
            (502, 'Wireless Lapel Mics', 'Event Tools', 800, '/static/images/event_tool1.jpg', 'Crystal clear sound for presenters.', 45000),
            (503, '4K Smart Projector', 'Event Tools', 1500, '/static/images/event_tool2.jpg', 'High-definition viewing experience.', 85000),
            (504, 'Digital Audio Mixer', 'Event Tools', 2000, '/static/images/event_tool4.jpg', 'Professional 16-channel mixer.', 95000),
            (505, 'Fog & Party Machine', 'Event Tools', 1200, '/static/images/event_tool5.jpg', 'Heavy smoke and bubble effects.', 35000),
            (506, 'Live Streaming Gear', 'Event Tools', 3500, '/static/images/event_tool6.jpg', 'Encoders and multi-cam setup.', 120000)
        ]
        for p in all_products:
            cur.execute("INSERT INTO products (product_id, name, category, price, image_path, description, market_price) VALUES (:1, :2, :3, :4, :5, :6, :7)", p)

        # 4. CUSTOMERS
        customers_data = [
            (1, 'Rahul Sharma', '9876543210', 'rahul@gmail.com', 'Pune', 'pass123'),
            (2, 'Anita Patil', '9123456789', 'anita@gmail.com', 'Mumbai', 'pass123'),
            (3, 'Vikram Singh', '8888888888', 'vikram@gmail.com', 'Delhi', 'pass123'),
            (4, 'Priya Mehta', '7777777777', 'priya@gmail.com', 'Bangalore', 'pass123'),
            (5, 'Suresh Kumar', '9999999999', 'suresh@gmail.com', 'Chennai', 'pass123')
        ]
        for c in customers_data:
            cur.execute("INSERT INTO customers (customer_id, customername, phone, email, address, password) VALUES (:1, :2, :3, :4, :5, :6)", c)

        # 5. GENERATE 15 BOOKINGS
        print("- Generating 15 Historical Bookings...")
        today = datetime.now()
        history = [
            (901, 1, 101, 4500, today-timedelta(days=20), 'Returned'),
            (902, 2, 201, 5500, today-timedelta(days=18), 'Returned'),
            (903, 3, 301, 3500, today-timedelta(days=16), 'Returned'),
            (904, 4, 401, 15000, today-timedelta(days=14), 'Confirmed'),
            (905, 5, 501, 2500, today-timedelta(days=12), 'Confirmed'),
            (906, 1, 102, 2800, today-timedelta(days=10), 'Confirmed'),
            (907, 2, 202, 4200, today-timedelta(days=8), 'Confirmed'),
            (908, 3, 303, 5500, today-timedelta(days=6), 'Confirmed'),
            (909, 4, 109, 3800, today-timedelta(days=4), 'Confirmed'),
            (910, 5, 204, 3800, today-timedelta(days=2), 'Confirmed'),
            (911, 1, 506, 3500, today+timedelta(days=1), 'Pending'),
            (912, 2, 402, 8000, today+timedelta(days=3), 'Pending'),
            (913, 3, 110, 2900, today+timedelta(days=5), 'Pending'),
            (914, 4, 203, 3200, today+timedelta(days=7), 'Pending'),
            (915, 5, 302, 2200, today+timedelta(days=10), 'Pending')
        ]
        
        for bid, cid, pid, price, r_date, status in history:
            cur.execute("INSERT INTO bookings (booking_id, customer_id, total_price, rent_date, return_date, status) VALUES (:1, :2, :3, :4, :5, :6)", 
                        (bid, cid, price, r_date, r_date + timedelta(days=3), status))
            cur.execute("INSERT INTO booking_details (booking_id, product_id, quantity, price) VALUES (:1, :2, 1, :3)", (bid, pid, price))
        
        # 6. ORACLE VIEW
        cur.execute("""
            CREATE OR REPLACE VIEW vw_all_bookings AS
            SELECT b.booking_id, c.customername, p.name AS product, b.status, b.total_price, b.rent_date
            FROM bookings b
            JOIN customers c ON b.customer_id = c.customer_id
            JOIN booking_details bd ON b.booking_id = bd.booking_id
            JOIN products p ON bd.product_id = p.product_id
        """)

        conn.commit()
        print("SUCCESS! Error-Free Master Restoration Complete.")

    except Exception as e:
        print(f"Master Sync failed: {e}")
    finally:
        if 'cur' in locals(): cur.close()
        if 'conn' in locals(): conn.close()

if __name__ == "__main__":
    sync_database()
